name: Build

on:
  push:
    branches:
    - "fix-building-wheel"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Ubuntu-20.04]
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.10'
        
      - name: Set up QEMU
        if: runer.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@2.7.0
        env:
          CIBW_ARCHS_LINUX: aarch64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
