name: Build

on:
  push:
    branches:
    - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Ubuntu-20.04, windows-2019, macos-11]
    
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@2.8.1

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
